version: '3.8'

services:
  crm:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL
      - NEXT_PUBLIC_SUPABASE_URL
      - NEXT_PUBLIC_SUPABASE_ANON_KEY
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
    volumes:
      - ./Crm/public:/app/public
      - ./Crm/content:/app/content
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3