version: "1.0.0"
services:
  app:
    type: docker
    dockerfile: Dockerfile
    port: 3000
    env:
      - DATABASE_URL
      - NEXT_PUBLIC_SUPABASE_URL
      - NEXT_PUBLIC_SUPABASE_ANON_KEY
      - NEXTAUTH_SECRET
      - NEXTAUTH_URL
    healthcheck:
      path: /api/health
      port: 3000
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s